### ISSUE TITLE
ServiceInstanceGuidSuffix fails when binding backing apps due to concatenated guids

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#205]
I've been testing the ServiceInstanceGuidSuffix target today and been getting failures. My appbroker config looks like this:

```
    appbroker:
      services:
      - service-name: ${config-server.service-name}
        plan-name: ${config-server.plan-name}
        target:
          name: <%= p("config_server_broker.target") %>
        apps:
        - name: config-server
          path: file:/var/vcap/data/config-server-broker/BOOT-INF/classes/apps/config-server.jar
          properties:
            memory: 1G
          services:
          - service-instance-name: mirror-svc
        services:
        - service-instance-name: mirror-svc
          name: ${config-server.mirror-service-name}
          plan: standard
          parameters-transformers:
          - name: ParameterMapping
            args:
              include: git,vault,composite,update-git-repos
```

where `<%= p("config_server_broker.target") %>` resolves to `ServiceInstanceGuidSuffix` in this deployment.

Here's my service list - I've tried and failed to create two `p.config-server` instances called `mycs` and `mycs2`:

```
±  |gareth/Switch_to_use_single_space_for_all_service_instances_on_PWS-414 {10} ✓| → cf s
Getting services in org p-spring-cloud-services / space instances as admin...
OK

name                                              service                  plan       bound apps   last operation
mycs                                              p.config-server          standard                create failed
mirror-svc-d34ef22d-8488-4837-899d-13d1334071ab   p.mirror-service-alpha   standard                create succeeded
mycs2                                             p.config-server          standard                create failed
mirror-svc-c9e741f8-25d1-447a-9c86-438e79121406   p.mirror-service-alpha   standard                create succeeded
```

From our broker log:
```
2019-02-20 15:13:14.167 ERROR 7 --- [ry-client-nio-1] o.s.c.a.d.BackingAppDeploymentService    : Error deploying applications [BackingApplication{name='config-server-c9e741f8-25d1-447a-9c86-438e79121406', path='file:/var/vcap/data/config-server-broker/BOOT-INF/classes/apps/config-server.jar', properties={memory=1G}, environment={}, services=[org.springframework.cloud.appbroker.deployer.ServicesSpec@49cde3f0], parametersTransformers=[], credentialProviders=[]}] with error 'Service instance mirror-svc-d34ef22d-8488-4837-899d-13d1334071ab-c9e741f8-25d1-447a-9c86-438e79121406 could not be found'
```

The name of the service instance being bound is incorrect here: `mirror-svc-d34ef22d-8488-4837-899d-13d1334071ab-c9e741f8-25d1-447a-9c86-438e79121406`. We should be binding `config-server-c9e741f8-25d1-447a-9c86-438e79121406` to `mirror-svc-c9e741f8-25d1-447a-9c86-438e79121406` here, but we've somehow picked up the guid of the other `mirror-svc` instance and incorrectly added it to the expected service name.

I'm still investigating this because I'm sure I've seen it work before. One theory is that this happens if an existing `SpacePerServiceInstance` broker is redeployed with the `ServiceInstanceGuidSuffix` target, so I'm going to try a clean deployment next and see what happens.
