### ISSUE TITLE
Update reference docs to reflect apps and services hierarchy

### ISSUE THREAD

**Issue by mheath** [spring-cloud/spring-cloud-app-broker#242]
Currently App Broker users can't create a backing service instance unless it is bound to an application. App Broker users are also unable to have multiple apps bind to the same backing service instance.

Rather than using configuration like:

```
spring.cloud.appbroker.services:
- service-name: example
  plan-name: standard
  apps:
  - name: example-app1
    services:
    - service-instance-name: ...
      name: ...
      plan: ...
```

consider using configuration like:

```
spring.cloud.appbroker.services:
- service-name: example
  plan-name: standard
  services:
    service1:
      service-instance-name: backing-service-1
      name: ...
      plan: ...
    service2:
      service-instance-name: backing-service-2
      name: ...
      plan: ...
    unbound-service-instance:
      service-instance-name: service3
      name: ...
      plan: ...
  apps:
  - name: example-app1
    bound-service-instances:
      service1:
      service2:
        binding-parameters: { ... }
  - name: example-app2
    bound-service-instances:
      service1:
```
