### ISSUE TITLE
Map Object value to JSON string in EnvironmentMappingParametersTransformer

### ISSUE THREAD

**Issue by LittleBaiBai** [spring-cloud/spring-cloud-app-broker#259]
GIVEN that a backing app is specified with a parameters transformer that maps parameters to backing app environment variables
```
spring:
  cloud:
    appbroker:
      app:
        parameters-transformers: 
        - name: EnvironmentMapping
           args: 
           - include: parameter1,parameter2,parameter3
```
WHEN I pass in -c parameters `-c '{"parameter1": ["value1"], "parameter2": {"key2": "value2"}, "parameter3": [{"key3": "value3"}]}'`
THEN I can see the SPRING_APPLICATION_JSON environment variable for the backing app containing:

```
{
	"parameter1": "[\"value1\"]",
	"parameter2": "{\"key2\": \"value2\"}",
	"parameter3": "[{\"key3\": \"value3\"}]"
}
```
