### ISSUE TITLE
Spring Cloud App Broker Documentation is incorrect for `parameters-transformers`

### ISSUE THREAD

**Issue by ahmedmq** [spring-cloud/spring-cloud-app-broker#397]
https://docs.spring.io/spring-cloud-app-broker/docs/1.1.1.RELEASE/reference/#service-instance-parameters

The documentation for parameter-transformers show `args` as an array element
```
  parameters-transformers:
                - name: EnvironmentMapping
                  args:
                    - include: parameter1,parameter2
                - name: PropertyMapping
                  args:
                    - include: count,memory
```
